### PR TITLE
Added basic layout from figma

### PR DESCRIPTION
**Pull request by wkande**
This branch changes the landing page to use some layout features from a figma page.

----- Do not merge this PR -----
A final approval by T is needed.
--------------------------------

### CODE REVIEW

**Review by dcroote — COMMENTED** [review]
I'm not sure if this is ready for review, but it might be worth noting the mobile (android) view of the new section isn't rendering cleanly (screenshot).

image

**Comment by wkande** [comment]
@dcroote can you try it again on the Android device

**Comment by dcroote** [comment]
> @dcroote can you try it again on the Android device

Looks good now 👍

**Comment by wkande** [comment]
These changes will not be implemented.

**Pull request closed without merging**
