### PR TITLE
Add new chains qrng

### PR DESCRIPTION
**Pull request by Ashar2shahid**
The chains in https://docs.api3.org/reference/airnode/latest/ are fetched from the package which won't be updated until a new airnode version is released. Not sure what to do about that

### CODE REVIEW

**Comment by wkande** [comment]
@Ashar2shahid : Looks like we need to run the `axiosBuildScripts.js` file. Not sure what you mean about a new Airnode release. Anyway if we merge this PR I can follow-up with issue #610 which will encompass a lot of things to get the docs up-to-date including the execution of `axiosBuildScripts.js`.

**Review by dcroote — APPROVED** [review]
@Ashar2shahid - I fixed the formatting in #612, looks like you might not have rebased before this PR. I think it should be fine as long as you "Squash and merge" this PR.

@wkande - @Ashar2shahid is right in that running `yarn axios:build` on this PR doesn't change anything (I confirmed this) because the recent Airnode PR containing new chain deployments (https://github.com/api3dao/airnode/pull/1864) isn't part of an Airnode release (yet) and therefore the build script doesn't pull those new addresses. 

I'm going to work on releasing Airnode v0.12.1 soon and the deployment PR will be part of that, after which the build script will populate the addresses. Let me know if you think it can't wait.

**Comment by wkande** [comment]
@dcroote - I probably should wait until after Airnode `v0.12.1` then to do this issue #610 which will upgrade the VitePress framework. Any idea when Airnode `v0.12.1` will happen?

**Comment by dcroote** [comment]
In the next couple of weeks. I'm not sure how an Airnode release ties to #610, I'd recommend just going ahead.

**Comment by Ashar2shahid** [comment]
@dcroote @wkande thanks for the review, I think it's alright to push this and wait for v0.12.1 to be out to fix the ` https://docs.api3.org/reference/airnode/latest/` page

**Pull request merged**
