### PR TITLE
Added new chains + Bump api3/chains to v4.4.0

### PR DESCRIPTION
**Pull request by vanshwassan**
- Added `blast-sepolia-testnet` for Testnet Random Numbers QRNG Provider.
- Added `lightlink` for Quintessence QRNG Provider.
- Bump api3/chains to v4.4.0

### CODE REVIEW

**Review by dcroote — COMMENTED** [review]
I'm happy to close https://github.com/api3dao/vitepress-docs/pull/701 since these two overlap, but can you incorporate the update I made to the migration guide here?

**Review by dcroote — APPROVED** [review]
Ignore my comment above, I'll just merge #701 after you merge this PR.

**Review by wkande — APPROVED** [review]
LGTM and thanks for the changes

**Comment by vanshwassan** [comment]
Just checked and fixed the `minConfirmations` for LightLink Goerli Testnet for Testnet Random Numbers Provider.

**Review by Ashar2shahid — APPROVED** [review]

**Pull request merged**
