### PR TITLE
The MetaMask struggle continues

### PR DESCRIPTION
**Pull request by wkande**
MetaMask has two presentations, one is an overlay that is always on top of the browser and the other is a popup which can disappear behind the browser if the user is not careful. The popup is forced open by eht_requestAccounts or wallet_requestPermissions. The former is a nightmare because calling it twice with the popup behind causes things to lock up. The user can only fix it by using the overlay. The later works better but still requires teh user to use the overlay for adjustments.

### CODE REVIEW

**Comment by Siegrift** [comment]
Mhh, what are you trying to achieve with MM?

**Comment by wkande** [comment]
@Siegrift : So this a component requested by Ashar and Ben. They are building out new guides for the docs and want an interface to MetaMask. It appears we may now have a handle on things and can do want Ashar wants to accomplish which is:

- Deploy a contract to Goerli only.
- Call [n] number of functions or get on a public variable.

See the (not finished component and it docs for use **[here](https://vitepress-docs.web.app/dev/using-metamask/)**)

**Comment by Siegrift** [comment]
I am unable to connect to MM. I don't see any connect button nor instructions how to connect. Am I missing something? (I like the idea of the widget though).

**Comment by wkande** [comment]
@Siegrift - There should be two widgets at the top of the page and one at the bottom. https://vitepress-docs.web.app/dev/using-metamask/

The top two are different  implementations. One (on left) uses the MetaMask overlay and the other (on right) MetaMask popup. I seem to remember you are on a Mac wit apple silicon, same as me, so they should be working. If not we are still working on it and I will keep you updated.

**Comment by Siegrift** [comment]
Just fyi:
image

And I am not able to connect to any of the widgets. 

> If not we are still working on it and I will keep you updated.

Yeah, I stumbled on this just by accident and was curious. Let me know if you need my help/testing.

**Pull request merged**
