### PR TITLE
Technical dAPI self-funded guides

### PR DESCRIPTION
**Pull request by Ashar2shahid**
I've covered the following in detail:

- Funding a self-funded dAPI

- Deploying a proxy for a self-funded dAPI

- Reading a self-funded dAPI proxy

The Gelato code isn't perfect , so I will put up that piece once I finalize the contract code. I added the old code for reference.

Also I merged Vansh's branch into this which updates the airnode guides and QRNG guides

### CODE REVIEW

**Comment by wkande** [comment]
@Ashar2shahid What will the do? You added it to `package.json`.
``` 
"resolutions": {
    "watchpack": "1.6.1"
 },
```

**Comment by wkande** [comment]
@Ashar2shahid and @KenCarvAPI - Can we have a google meeting on this PR. Some topics:

- There are existing guides that will get over-written and new ones added.
- Guide formatting, difference between how-to and tutorials.
- `watchpack`

**Comment by Ashar2shahid** [comment]
> @Ashar2shahid What will the do? You added it to `package.json`.
> 
> ```
> "resolutions": {
>     "watchpack": "1.6.1"
>  },
> ```

its meant to enable hot-reload in vite-press which doesn't work atm

**Comment by wkande** [comment]
@Ashar2shahid - Are you ready for this PR to be merged? If so it appears there are conflicts with `sidebar.js`. Are you able to fix them or do you want me to do so. I might take me a few days but I do not think we are in any hurry.

**Comment by Ashar2shahid** [comment]
@wkande As you can see, I've added a lot of commits that add merge conflicts, this PR basically revamps the entirety of the guides section. We are in no hurry to merge it and we can discuss the changes in a meeting if you want. The goal was to make the guides section more inviting and have a consistent flow between the sections.

**Comment by wkande** [comment]
@Ashar2shahid - I would think that Firebase will not build a preview because of the conflicts. Anyway we should try and get the convicts resolved so I can merge this. It will be useful for everyone to see where we are at.

**Comment by Ashar2shahid** [comment]
@wkande agreed, I should have this ready by tomorrow

**Comment by Ashar2shahid** [comment]
@wkande this should be good to merge, sorry for the extra commit, I rebased on top of master

**Comment by wkande** [comment]
@Ashar2shahid So I see a lot of new files for guides and the removal of some older ones from `sidebar.json`. If the older files still exist in the `/docs` folder they will still build along with the ones you wish to present. This becomes an issue as the index script will index these older files and present them in the search overlay to the user if found. Unused files need to be removed to the `/archive` folder.

Having said all that I can move them after the merge. This way it is easier for me to see what you have removed. So are we ready to merge?

**Pull request merged**
