### PR TITLE
Added Calling an Airnode guide

### PR DESCRIPTION
**Pull request by vanshwassan**
I've added the Calling an Airnode guide under the Airnode section. Also added it to the sidebar.

### CODE REVIEW

**Comment by dcroote** [comment]
@vanshwassan is there a reason you're working from your own fork instead of a branch within this repo? The Firebase Action build fails because of a GitHub security policy that doesn't allow PRs from forks to access repo secrets.

**Comment by wkande** [comment]
@vanshwassan I am a little worried about the prettier changes to the search files that I am working on. I see that prettier updated so many files. The files for search are changing constantly while I work on them. Best not to commit these files if they change on your end for now. Maybe @dcroote has a suggestion to this issue.

**Comment by wkande** [comment]
My next commit will delete the search build files from `/.vitepress`. They will live in `./libs/search-files`. I will then add them to gitignore as they do not need to be in the repo. This will help with the prettier issue

**Comment by wkande** [comment]
I think the conflicts will be difficult to manage but maybe you can figure it out. It might be possible to clone the repo as it its today, create a new working branch and then copy past your files from your old local repo over to the new cloned repo.

**Comment by vanshwassan** [comment]
Okay, will make another PR with all the changes. 👍🏻

**Comment by dcroote** [comment]
@wkande - I think while the search files are under development `.gitignore` works fine. Once they stabilize they could be added to the repo, and optionally added to `.prettierignore`.

**Comment by wkande** [comment]
> Edit: @wkande - If the files are under .gitignore, won't you not be able to test the search functionality in previews and on the live site? Alternatively they could be kept in the repo and added to .prettierignore.

The file are actually used to build the index and are then throw away. See the script **[here](https://github.com/api3dao/vitepress-docs/blob/main/libs/flexsearchBuildIndexes.js)**. So anyone could run the script locally, the support files are built, then the indexes are built from the support files. Only the index gets push back to the repo.

**Comment by dcroote** [comment]
Ah ok, thanks for clarifying!

**Pull request closed without merging**
