### PR TITLE
610 update framework rc.10

### LINKED ISSUE #610: upgrade framework to 1.0.0-rc.10 (2023-08-28)
Full site upgrade to [1.0.0-rc.10](https://github.com/vuejs/vitepress/compare/v1.0.0-rc.9...v1.0.0-rc.10) (2023-08-28)

Also include:
- Axis script
- Flex indexes
- Link validation

### PR DESCRIPTION
**Pull request by wkande**
Closes #610 

- I changed the message on the landing page. Suggestion?
- The new framework changed to use indigo for link colors and underlined them, I changed it back [here](https://github.com/api3dao/vitepress-docs/blob/610-update-framework-rc.10/docs/public/styles/api3.css#L7-L20)
- The green color was changed to 4 variations to choose from. I used the first
- They changed the text for  inline code blocks (`code`) to a lighter green. I do worry people will think it is a link as well. The only saving grace is the gray background. This could possibly be changed. Either by trying to change the text color or by bringing back the underlining of links. The later being the default of the framework and my preferred behavior.
- Code blocks in light mode now use a gray background rather than black.
- build time now takes 12 seconds

### CODE REVIEW

**Review by dcroote — CHANGES_REQUESTED** [review]
> I changed the message on the landing page. Suggestion?

I like it.

> They changed the text for inline code blocks (code) to a lighter green. I do worry people will think it is a link as well. The only saving grace is the gray background. This could possibly be changed. Either by trying to change the text color or by bringing back the underlining of links. The later being the default of the framework and my preferred behavior.

Sadly I think we have to change this: the visual difference between links and code blocks is very small. 

Somehow we've also lost nice JSON formatting (though solidity, js, and shell seem fine). [For example](https://docs.api3.org/guides/airnode/deploy-airnode/deploy-aws/#_3-prepare-configuration-files):

Before:
image

And after:
image

**Comment by wkande** [comment]
@dcroote : So this release of Vitepress is using **[Shiki](https://vitepress.dev/guide/markdown#syntax-highlighting-in-code-blocks)** for syntax highlighting. It appears that Shiki uses a very subtle highlight scheme for `json`. 

- Notice that keys are in blue and values in a black (except for boolean) in light mode
- In dark mode it uses two different shades of blue but they are close to each other in contrast.

Granted it may not be ideal but I am not sure what to do here. I did see that using `berry` rather than `json` does improve things. Should we consider using another language definition for `json` if we can find one that we like?

**Comment by wkande** [comment]
For the most part `berry` adds a red colon to separate the key and value.

Screenshot 2023-09-06 at 5 36 44 AM

**Comment by dcroote** [comment]
Thanks for investigating @wkande . I played around a bit and though not ideal, I think we should just stick with `json`. If a user decides to edit a config they'll do so using they're preferred editor, many of which come with better formatting, linting, etc.

I do still think the code block and link colors are too close though.

**Comment by wkande** [comment]
@dcroote I will work on the inline code block color today.

**Comment by wkande** [comment]
@dcroote - The inline code blocks are now fixed using:

```js
/** 
 * Starting with Vitepress rc.10, inline code blocks used the color green.
 * Moved to use the default theme color. Works best with light/dark modes 
*/
code {
  color: inherit !important;
}
```

**Comment by wkande** [comment]
@dcroote - How about now `color: #909090 !important;`

**Comment by dcroote** [comment]
I find that difficult to read in light and dark mode because of lack of contrast. Can we just go back to what the last Vitepress used (and our current live-site uses), i.e.:

Dark theme code background: #313136
Dark theme code text: #c9def1

Light theme code background: #f6f6f7
Light theme code text: #476582

(via `--vp-c-mute` and `--vp-c-text-code`)

**Comment by wkande** [comment]
@dcroote The color codes you listed above seem different to both the live-site and preview sites. Try this **[color code viewer](https://www.hexcolortool.com/#476480)**. 

Anyway I never liked the way live-site displays inline code blocks, the background is much too close to the page color. By keeping in mind your comment about contrast I came up with these.
```
:root {
  --vp-code-color: #36454f;
}

:root.dark {
  --vp-code-color: whitesmoke;
  --vp-code-bg: #36454f;
}
```

- For light I only changed the font color, the background seems fine
- For dark mode I changed both the font and background

This seems to give us the contrast that was missing.

**Review by dcroote — APPROVED** [review]
These look good, nice selection 👍

**Pull request merged**
